mod options;
mod options_for_operator_with_adjacency_matrix_argument;
mod options_for_operator_with_adjacency_matrix_arguments;
mod options_for_operator_with_adjacency_matrix_as_left_argument;
mod options_for_operator_with_adjacency_matrix_as_right_argument;

pub use options::*;
pub use options_for_operator_with_adjacency_matrix_argument::*;
pub use options_for_operator_with_adjacency_matrix_arguments::*;
pub use options_for_operator_with_adjacency_matrix_as_left_argument::*;
pub use options_for_operator_with_adjacency_matrix_as_right_argument::*;
